FROM ubuntu:20.04
RUN apt-get update && yes | apt-get update
RUN apt-get install -y build-essential

# 1. install library for dependency
# 1.1  libboost_1_69 for SALT simulator
WORKDIR /to_install
COPY ./to_install_uniq/boost_1_69_0.tar.bz2 /to_install
RUN tar xvfj boost_1_69_0.tar.bz2
WORKDIR /to_install/boost_1_69_0
RUN ./bootstrap.sh --prefix=/usr
RUN ./b2 cxxflags=-fPIC cflags=-fPIC link=static -a
RUN ./b2 install
WORKDIR /
RUN rm -rf /to_install

# 1.2  python for simulator
RUN apt-get update
RUN apt-get install -y python3.8 python3-pip
RUN apt-get install -y python3.8-dev
RUN ln -s /usr/bin/python3.8 /usr/bin/python

RUN python --version
RUN python -m pip install --upgrade pip

# 1.3 for convenience, install vim editor
RUN apt-get update
RUN apt-get install -y vim

# 2. install simulator
# 2.1 install SALT simulator
COPY ./to_install_uniq/salt/bin /uniq/simulator/salt/bin
COPY ./to_install_uniq/salt/tools /uniq/simulator/salt/tools
COPY ./to_install_uniq/salt/sample /uniq/simulator/salt/sample

# 4. set environment variable
# 4.1 set env variable for SALT
ENV SALT_HOME=/uniq/simulator/salt
ENV PYTHONPATH=$SALT_HOME/tools:$PYTHONPATH
ENV PATH=$SALT_HOME/bin:$PATH
#
# 5. set working dir
WORKDIR /uniq/simulator/salt

# 6. execute
# ENTRYPOINT ["/bin/bash", "-l", "-c"] 
